# ========================================
# Ralph Cuts Academy - Backend
# ========================================

server.port=8080

# ========================================
# PostgreSQL - pgAdmin Local
# ========================================
spring.datasource.url=jdbc:postgresql://localhost:5432/barberia_db
spring.datasource.username=postgres
spring.datasource.password=9623
spring.datasource.driver-class-name=org.postgresql.Driver

# ========================================
# JPA / Hibernate
# ========================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ========================================
# JWT
# ========================================
jwt.secret=UmFscGhDdXRzQWNhZGVteTIwMjVTZWNyZXRLZXlGb3JKV1RBdXRoZW50aWNhdGlvbk11c3RCZUE=
jwt.expiration=86400000

# ========================================
# CORS
# ========================================
cors.allowed-origins=http://localhost:4200,http://localhost:3000

# ========================================
# Bunny Stream
# ========================================
bunny.stream.api-key=${BUNNY_API_KEY:4b0a61d5-0719-4c99-84115b982721-330b-4660}
bunny.stream.auth-key=${BUNNY_AUTH_KEY:c868ce35-beec-4656-bbbf-4a66b19242e9}
bunny.stream.library-id=${BUNNY_LIBRARY_ID:590927}
bunny.stream.cdn-hostname=${BUNNY_CDN_HOSTNAME:vz-e7443a92-10a.b-cdn.net}
bunny.stream.api-url=https://video.bunnycdn.com
